### PR TITLE
Add `osx` platform to podspec

### PR DESCRIPTION
**Pull request by maxsz**

### CODE REVIEW

**Comment by nubbel** [comment]
The CI failure seems to be completely unrelated to this change.
@1martijnwalraven Can you please retrigger the CI build?

**Comment by martijnwalraven** [comment]
@nubbel: Restarted, let's hope this helps.

**Comment by nubbel** [comment]
It is just a timing issue with the server integration tests.

**Comment by martijnwalraven** [comment]
@nubbel: Sorry I haven't done anything with this yet, but I've been on the road and plan to take some time this weekend to look into and merge the pull requests, and hopefully get the CI working again.

**Comment by martijnwalraven** [comment]
@nubbel: Tests are passing again locally and in CI, for both iOS and macOS now. I haven't attempted installing through CocoaPods yet, but let me know if anything is broken.

**Comment by nubbel** [comment]
hey @martijnwalraven, thank you very much!

**Comment by maxsz** [comment]
Hi @martijnwalraven, thanks for merging 🍻
Could you also update the podspec on cocoapods (maybe also with a 0.3.2 release)?

**Comment by martijnwalraven** [comment]
@maxsz: Just released 0.3.2 and pushed the podspec. Let me know if that works for you!

**Comment by maxsz** [comment]
It's working perfectly. Thanks again!

**Pull request merged**
