### PR TITLE
Updating podspec

### PR DESCRIPTION
**Pull request by romainbiard**
All is in the title, allowing Apollo to be embedded in tvOS apps.

Thanks for you review.
Romain

### CODE REVIEW

**Comment by romainbiard** [comment]
BTW should require a new cocoapod release to spread this new availability.
👍 
Thanks for your feedback.

**Comment by martijnwalraven** [comment]
Thanks! I'm in the process of finalizing normalized caching support, but I'll make a new release as soon as that is done. Shouldn't be more than one or two days.

**Comment by romainbiard** [comment]
Excellent !
Thank you for the reactivity.

I think you were discussing about caching with my colleague Jan, right ?

Have a great day.
Romain

**Comment by martijnwalraven** [comment]
Yes, I mentioned normalized caching in an email to Jan. Definitely interested in discussing it further. I'm also writing a blog post about it.

**Pull request merged**
